server:
  port: 8083

spring:
  application:
    name: product-service
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/micro-product
    username: root
    password: WezersHero22
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    addresses: localhost:5672

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true